name: iToF-RGB
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.10.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.6
  - tqdm=4.64.1
  - tensorboard=2.10.0
  - pillow=9.2.0
  - pandas=1.5.0
  - kornia=0.6.7
  - matplotlib=3.6.0
  - scipy=1.9.1
  - pip:
    - pyyaml
    - pytorch-msssim
    - timm